name: Dastardly Action

on: workflow_dispatch

jobs:
  dastardly:
    runs-on: ubuntu-latest
    steps:
    - name: Run Dastardly Action Step
      uses: PortSwigger/dastardly-github-action@main
      with:
        target-url: 'https://ginandjuice.shop'
